name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: Test-${{ github.ref }}
  cancel-in-progress: true

env:
  RUN_MYPY: 'false'

jobs:
  tests:
    name: ${{ matrix.python_version }} ${{ matrix.os }} numpy=${{ matrix.numpy }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Note: ruamel.yaml does not support Python 3.13t
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
        numpy: [true]
        include:
          - os: ubuntu-latest
            python_version: "3.9"
            numpy: false
          - os: ubuntu-latest
            python_version: "3.14"
            numpy: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Configure Python version
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run mypy
        if: ${{ env.RUN_MYPY == 'true' }}
        run: |
          python -m pip install mypy
          python -m mypy srsly

      - name: Install package
        run: python -m pip install .

      - name: Test that numpy was not installed
        shell: bash
        run: if pip list | grep -q '^numpy'; then exit 1; fi

      - name: Install numpy
        if: ${{ matrix.numpy }}
        run: python -m pip install numpy

      - name: Install test requirements
        run: python -m pip install pytest

      - name: Run tests
        run: pytest
